name: Test NPM Package

on:
  pull_request:
    branches: ['main']

jobs:

  test_cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build
    - run: npm run test
    - run: npm pack

  tsc_components:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: cd ./components
    - run: npx tsc
    - run: npm pack
