name: Publish NPM Package

on:
  push:
    branches: ['main']
    paths: ['package.json']

jobs:

  compile_cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: |
          ./
          !node_modules/**

  test_cli:
    runs-on: ubuntu-latest
    needs: compile_cli
    steps:
    - uses: actions/download-artifact@master
      with:
        name: build-artifact
        path: ./
    - run: npm run test

  test_components:
    runs-on: ubuntu-latest
    needs: compile_cli
    steps:
    - uses: actions/download-artifact@master
      with:
        name: build-artifact
        path: ./
    - run: cd components && tsc

  publish:
    runs-on: ubuntu-latest
    needs: [test_cli, test_components]
    steps:
    - uses: actions/download-artifact@master
      with:
        name: build-artifact
        path: ./
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
