name: Publish NPM Package

on:
  push:
    branches: ['main']
    paths: ['package.json']

jobs:

  test-pkg:
    name: Test package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: "1.36.2"
    - run: |
        cd tests
        deno task test_predeploy

  publish-npmjs:
    runs-on: ubuntu-latest
    needs: test-pkg
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gh:
    runs-on: ubuntu-latest
    needs: test-pkg
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://npm.pkg.github.com
    - run: npm ci
    - run: npm run build
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
